# Generated by Django 3.0.5 on 2020-04-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
